# version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ensolvers_notes_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ensolvers_notes
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ensolvers_notes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: ensolvers_notes
      PORT: 3000
      FRONTEND_URL: http://localhost:4173
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
    expose:
      - 4173
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: